name = "frontend"
main = ".open-next/worker.js"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

# Environment variables
[vars]
# Add your environment variables here

