name = "frontend"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".open-next/worker"

# Environment variables
[vars]
# Add your environment variables here
