name: CI Tests

on:
  pull_request:
    # Run on all PRs to any branch
    paths:
      - "src/**"
      - "cypress/**"
      - "package.json"
      - "bun.lockb"
      - "tsconfig.json"
      - "next.config.ts"
      - "next.config.js"
      - ".eslintrc*"
      - "eslint.config.*"
      - "tailwind.config.ts"
      - "postcss.config.js"
      - "i18n/**"
      - ".github/workflows/ci-tests.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Validate translations
        run: node scripts/validate-translations.js
        continue-on-error: true

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: bun run dev
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          config-file: cypress.config.ts
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL || 'http://localhost:9000' }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000' }}

      - name: Upload Cypress screenshots on failure
        uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos on failure
        uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run TypeScript type checking
        run: bun run type-check

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint
