name: Auto-translate Locales with DeepL

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/i18n/locales/en.json'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest
    # Only run on PRs from the same repository (not forks)
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install --save-dev deepl-node --legacy-peer-deps

      - name: Run translation sync
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: |
          node scripts/sync-translations.js

      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/i18n/locales/*.json

          if git diff --staged --quiet; then
            echo "No translation changes to commit"
            exit 0
          fi

          git commit -m "chore: sync translations with DeepL"
          git push
